
image: node:lts-stretch-slim
stages:
    - Build
    - Test

install_dependencies:
    stage: Build
    script: yarn install
    artifacts: 
        path:
            - node_modules

test_run:
    stage: Test
    script: 
        - CI=True yarn test

