image: node:lts-stretch-slim
stages:
    - Build
    - Test

install_dependencies:
    stage: Build
    script: 
        - yarn install:
    artifacts: 
        paths:
            - node_modules
    
    cache:
        key:
            files:
                - .yarn.lock
        paths: 
            - node_modules

linter:
    stage: Test
    script: 
        - CI=True yarn linter

unit_test:
    stage: Test
    script: 
        - CI=True yarn test

