image: node:lts-stretch-slim
stages:
    - Build
    - Test
    - Deploy

install_dependencies:
    stage: Build
    tags:
        - test-react
    script:
        - yarn install
        - yarn build
    artifacts: 
        paths:
            - node_modules
            - build
    cache:
        key:
            files:
                - .yarn.lock
        paths: 
            - node_modules

linter:
    stage: Test
    tags: 
        - test-react
    script: 
        - yarn linter

unit_test:
    stage: Test
    tags:
        - test-react
    script: 
        - CI=True yarn test

test_delpoy:
    stage: Deploy
    tags: 
        - deploy-node-js
    script:
        - DIR=/www/test-app/$(date +%Y-%m-%d_%k-%M-%S)   
        - mkdir -p $DIR
        - cp -r build $DIR
        - ln -fsnv /var$DIR /www/html

           
