image: node:lts-stretch-slim
stages:
    - Build
    - Test


install_dependencies:
    stage: Build
    tags:
        - test-react
    script:
        - yarn install
    artifacts: 
        paths:
            - node_modules
    cache:
        key:
            files:
                - .yarn.lock
        paths: 
            - node_modules


linter:
    stage: Test
    tags: 
        - test-react
    script: 
        - yarn linter

unit_test:
    stage: Test
    tags:
        - test-react
    script: 
        - CI=True yarn test


           
