image: node:lts-stretch-slim
stages:
    - Build
    - Test


stage: Build
    tags:
        - test-react
    script:
        - yarn install
    artifacts: 
        paths:
            - node_modules
    cache:
        key:
            files:
                - .yarn.lock
        paths: 
            - node_modules


linter:
    stage: Test
    tags: 
        - test-react
    script: 
        - yarn linter

unit_test:
    stage: Test
    tags:
        - test-react
    script: 
        - CI=True yarn test

linter_standard:
    stage: Test
    before_script:
        - ./standard_linter.sh 
    script:
        - yarn linter
    allow_failure: true
    after_script:
        - rm -f .eslintrc

           
