image: node:lts-stretch-slim
stages:
    - Build
    - Test

install_dependencies:
    stage: Build
    script: yarn install
    artifacts: 
        paths:
            - node_modules
    
    cache:
        key:
            files:
                - .yarn.lock
        paths: 
            - node_modules

linter:
    stage: Test
    script: 
        - CI=True linter

unit_test:
    stage: Test
    script: 
        - CI=True yarn test


    linter_standard:
    stage: Test
    before_script:
        - echo "{ 'extends': 'standard'}" >.eslintrc 
    script:
        - yarn linter
    allow_failure: true
    after_script:
        - rm -f .eslintrc
