stages:
    - Build
    - Test
    - Deploy
    - Revert


variables: 
    env: 'prod'
    new_deploy_dir: 'test-app/${env}_$CI_COMMIT_SHA'
    prev_deploy_dir: 'test-app/${env}_$CI_COMMIT_BEFORE_SHA'
    docker_html_path: 'www'
    deploy_subdir: 'html'
    REACT_APP_WEBSITE_PREFIX: ""


Build_PROD:
    image: node:14.15.0-stretch
    stage: Build
    tags:
        - test-react
    script:
        - yarn install
        - yarn build
        - mv build build_$env
    artifacts: 
        paths:
            - node_modules
            - build_$env
    cache:
        key:
            files:
                - .yarn.lock
        paths: 
            - node_modules

Build_stage:
    stage: Build
    tags:
        - test-react
    extends: Build_PROD
    variables:
        env: staging
        REACT_APP_WEBSITE_PREFIX: "[branch=$CI_COMMIT_BRANCH]"
        PUBLIC_URL: "/$CI_COMMIT_BRANCH"    



Delpoy_PROD:
    stage: Deploy
    tags: 
        - deploy-node-js
    script:   
        - mkdir -p /$docker_html_path/$new_deploy_dir
        - cp -r build_$env/. /$docker_html_path/$new_deploy_dir
        - cp -Pv /$docker_html_path/$deploy_subdir /$docker_html_path/$new_deploy_dir/prev-version
    only:
        - master

Deploy_staging:
    extends: Delpoy_PROD 
    variables: 
        deploy_subdir: staging/$CI_COMMIT_BRANCH
        env: staging
    when:
        always
    allow_failure: true
    only:
        - master
        - /^feature-.*/

activite_staging:
    extends: activate_prod
    variables:
        deploy_subdir: staging/$CI_COMMIT_BRANCH
        env: staging
    when: always
    only:
        - master
        - /^feature-.*/

activate_prod:
    stage: Deploy
    tags:
        - deploy-node-js
    script:
        - ln -fsnv /var/$docker_html_path/$new_deploy_dir /$docker_html_path/$deploy_subdir
    when: manual
    only:
        - master

revert_version:
    stage: Revert
    tags: 
        - deploy-node-js
    when: manual
    script:  
        - cp -Pv --remove-destination /$docker_html_path/$new_deploy_dir/prev-version /$docker_html_path/$deploy_subdir

revert_previous_version:
   stage: Revert
   tags:
       - deploy-node-js
   when: manual
   script:
       - cp -Pv --remove-destination /$docker_html_path/$prev_deploy_dir/prev-version /$docker_html_path/$deploy_subdir
